import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { expect, test } from '@playwright/test';

// G9 — pseudolocale overflow (INTERNATIONALIZATION-STANDARD §4 / §8).
//
// Loads each app view under an `en-XA`-style pseudolocale (~40% longer than
// English, bracketed with ⟦ … ⟧) and asserts nothing clips, truncates, or forces
// horizontal scroll on the UI chrome (header, tabs, filters, list, panels, forms,
// controls). This catches layouts that only fit because English is short — the
// failure mode the moment Spanish (or any longer locale) renders. Runs on desktop
// + mobile (Pixel 7) via the two config projects.
//
// The Leaflet map surface (`.map-canvas` / `.location-picker-map`) is EXCLUDED:
// its tiles/controls scroll and pan by design, so measuring them is meaningless.
//
// The pseudo catalog is generated by scripts/i18n/gen-pseudo.mjs (run before this
// spec via `npm run e2e:i18n`) and injected into the running react-intl provider
// through the VITE_I18N_TEST_HOOKS window hook, so it never enters production.

const HERE = dirname(fileURLToPath(import.meta.url));
const PSEUDO = JSON.parse(readFileSync(resolve(HERE, 'en-XA.generated.json'), 'utf8')) as Record<
  string,
  string
>;

const MARK = '⟦'; // every pseudo value carries this; its presence proves re-render

// Tab order in the nav (labels are pseudo-localized, so click by index).
const TABS = ['map', 'list', 'coverage', 'route', 'report', 'mine', 'moderate'] as const;

interface I18nTestHandle {
  setMessages: (messages: Record<string, string> | null) => void;
}

test.describe('G9 — pseudolocale overflow (en-XA, ~40% expansion)', () => {
  for (let i = 0; i < TABS.length; i++) {
    const tab = TABS[i];
    test(`${tab} view has no chrome clipping / horizontal scroll under en-XA`, async ({ page }) => {
      await page.goto('/');
      await page.evaluate(() => document.fonts.ready);

      // Inject + activate the pseudolocale (persists across tab switches: it's
      // provider state). Requires the VITE_I18N_TEST_HOOKS=1 build.
      await page.evaluate((bundle) => {
        const handle = (window as unknown as { __i18nTest?: I18nTestHandle }).__i18nTest;
        if (!handle) {
          throw new Error(
            'window.__i18nTest missing — the app must be built with VITE_I18N_TEST_HOOKS=1',
          );
        }
        handle.setMessages(bundle);
      }, PSEUDO);

      await page.waitForFunction((mark) => document.body.innerText.includes(mark), MARK);

      // Switch to the target view (by index — labels are pseudo, not English).
      await page.locator('.tabs button').nth(i).click();

      await page.evaluate(() => document.fonts.ready);
      await page.waitForTimeout(400);

      const offenders = await page.evaluate(() => {
        const EPS = 1.5; // sub-pixel rounding tolerance

        // Elements inside a Leaflet map surface pan/scroll by design — exclude them.
        const MAP_SELECTORS = ['.map-canvas', '.location-picker-map', '.leaflet-container'];
        const inMap = (el: Element): boolean =>
          MAP_SELECTORS.some((sel) => el.closest(sel) !== null);

        const problems: string[] = [];

        // 1) The page itself must not scroll horizontally.
        const doc = document.documentElement;
        if (doc.scrollWidth > doc.clientWidth + EPS) {
          problems.push(
            `page: horizontal scroll (scrollWidth ${doc.scrollWidth} > clientWidth ${doc.clientWidth})`,
          );
        }

        const describe = (el: Element): string => {
          const id = el.id ? `#${el.id}` : '';
          const cn = el.getAttribute('class');
          const cls = cn && cn.trim() ? '.' + cn.trim().split(/\s+/).join('.') : '';
          return `${el.tagName.toLowerCase()}${id}${cls}`;
        };
        const overflowsX = (el: Element): boolean => el.scrollWidth > el.clientWidth + EPS;

        for (const el of Array.from(document.querySelectorAll('body *'))) {
          if (inMap(el)) continue;
          const cs = getComputedStyle(el);
          if (cs.display === 'none' || cs.visibility === 'hidden') continue;
          if (el.clientWidth < 4 || el.clientHeight < 4) continue;

          const scroller = /(auto|scroll)/.test(cs.overflowX);
          const hasText = !!el.textContent && el.textContent.trim().length > 0;

          // A clipping container whose text is cut off horizontally.
          const clipsX = cs.overflowX === 'hidden' || cs.overflowX === 'clip';
          if (clipsX && hasText && overflowsX(el)) {
            problems.push(
              `${describe(el)}: clipped content (scrollWidth ${el.scrollWidth} > clientWidth ${el.clientWidth})`,
            );
          }

          // Text truncated by ellipsis or nowrap.
          const truncates = cs.textOverflow === 'ellipsis' || cs.whiteSpace === 'nowrap';
          if (truncates && !scroller && hasText && overflowsX(el)) {
            problems.push(
              `${describe(el)}: truncated text (scrollWidth ${el.scrollWidth} > clientWidth ${el.clientWidth})`,
            );
          }
        }

        // 2) The main layout columns explicitly: their content must fit.
        for (const sel of ['.app', '.app-main', '.filters', '.list-view', '.moderation', '.report-form', '.route-planner', '.coverage', '.my-reports']) {
          for (const el of Array.from(document.querySelectorAll(sel))) {
            if (inMap(el)) continue;
            const cs = getComputedStyle(el);
            if (cs.display === 'none' || /(auto|scroll)/.test(cs.overflowX)) continue;
            if (el.clientWidth < 4) continue;
            if (overflowsX(el)) {
              problems.push(
                `${describe(el)}: container overflow (scrollWidth ${el.scrollWidth} > clientWidth ${el.clientWidth})`,
              );
            }
          }
        }

        return [...new Set(problems)];
      });

      expect(offenders, `pseudolocale overflow on ${tab} view`).toEqual([]);
    });
  }
});
